name: CD - Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 'latest'

    - name: Build WebAssembly
      run: |
        mkdir -p build-wasm
        cd build-wasm
        emcmake cmake ..
        emmake make -j$(nproc)

    - name: Create Pages Directory
      run: |
        mkdir -p _site
        cp build-wasm/BreakOut.html _site/index.html
        cp build-wasm/BreakOut.js _site/
        cp build-wasm/BreakOut.wasm _site/

    - name: Create Landing Page
      run: |
        cat > _site/README.md << 'EOF'
        # BreakOut - Web Demo

        **Play Now**: [Launch BreakOut](index.html)

        ## Controls
        - **Arrow Keys / WASD**: Move paddle
        - **Space**: Launch ball
        - **ESC**: Restart

        ## About
        Classic brick-breaking arcade game built in C with SDL2.

        Originally designed for PS Vita, now playable in your browser via WebAssembly!

        **Source**: [github.com/kion-dgl/VitaBreak](https://github.com/kion-dgl/VitaBreak)

        ## Other Platforms
        - **PS Vita**: Download VPK from [Releases](https://github.com/kion-dgl/VitaBreak/releases)
        - **PortMaster** (Anbernic/handhelds): Download from [Releases](https://github.com/kion-dgl/VitaBreak/releases)
        - **Linux**: Build from source

        ---
        Built with ❤️ using SDL2 and Emscripten
        EOF

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '_site'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
